server:
  port: 8080

spring:
  application:
    name: llm-friend-chatbot
  ai:
    ollama:
      chat:
        # model: mistral:7b-instruct-v0.3-q8_0
        #model: deepseek-r1:14b
        model: llama3.1:8b
        # model: llama3.2:3b
        #model: gemma3:12b
de:
  sven:
    bayer:
      llm:
        friend:
          chatbot:
            llmName: Lumi
            maxDetailConversationMessagesHistory: 6
            maxConversationMessageHistory: 16
            maxSummarizationLength: 30
